# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-13 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('active', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Hat', 'Hat'), ('Shoe', 'Shoe'), ('Miscellaneous', 'Miscellaneous')], max_length=13)),
                ('gender', models.CharField(choices=[('Mens', 'Mens'), ('Womens', 'Womens'), ('Unisex', 'Unisex')], max_length=6)),
                ('season', models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.ProductColorVariation.image_upload_to)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizeVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.IntegerField()),
                ('size', models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('7', 'Size 7'), ('8', 'Size 8'), ('9', 'Size 9'), ('10', 'Size 10'), ('11', 'Size 11'), ('12', 'Size 12'), ('13', 'Size 13')], max_length=2, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductColorVariation')),
            ],
        ),
    ]
